name: Animagus
version: 0.0.0
description: Transform into an animal of your choice or even disguise as other players or blocks
author: silvinci
authors: [silvinci, _baam_, CubixCraft]
website: https://github.com/CubixCraft/Animagus

main: com.github.cubixcraft.Animagus.Main